import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: ['300', '400', '500', '700', '900']});
import Gitlab from "@/components/icons/gitlab";
import Github from "@/components/icons/github";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} flex flex-col flex-wrap gap-2 md:gap-10 sm:max-w-[640px] lg:max-w-[1024px] px-6 md:px-4 mx-auto`}>
        <div className="flex flex-row justify-between items-center bg-slate-200">
          <Link href={'/'} className="hover:bg-orange-400 inline-block w-10 h-10">
            <div className="flex flex-col items-center justify-center w-full h-full">
              <Image 
                  src={'/ck-high-resolution-logo-black-transparent.png'} 
                  height={40} 
                  width={40}
                  alt="logo"
                />
            </div>
          </Link>
          <div className="flex flex-row gap-2 items-center">
            <Gitlab /> 
            <Github />
          </div>
           
        </div>
        <div className="flex md:flex-row flex-wrap flex-col-reverse gap-10 lg:gap-20">
          <div className="flex flex-col gap-10">
            {/* <h4>
              By <span className="font-extrabold text-xs">CHOL KUANY</span>
            </h4> */}
            <ul className="flex flex-col items-end gap-2 cursor-pointer">
              <li className="font-extrabold text-xs hover:underline underline-offset-4 hover:text-orange-400">
                <Link href={'/contact'}>CONTACT</Link> 
              </li>
              <li className="font-extrabold text-xs hover:underline underline-offset-4 hover:text-orange-400">
                <Link href={'/portfolio'}> PORTFOLIO</Link> 
              </li>
            </ul>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
