import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col gap-10 sm:max-w-[640px] lg:max-w-[1024px] px-2 md:px-4 my-20 mx-auto dark:bg-slate-100 dark:text-black`}>
        <Link href={'/'} className="hover:bg-orange-400 inline-block w-10 h-10">
          <div className="flex flex-col items-center justify-center w-full h-full">
            <Image 
                src={'/ck-high-resolution-logo-black-transparent.png'} 
                height={40} 
                width={40}
                alt="logo"
              />
          </div>
        </Link>
        <div className="flex md:flex-row flex-wrap flex-col-reverse gap-10 lg:gap-20">
          <div className="flex flex-col gap-10">
            <h4>
              By <span className="font-extrabold text-xs">CHOL KUANY</span>
            </h4>
            <ul className="flex flex-col items-end gap-2 cursor-pointer">
              <li className="font-extrabold text-xs hover:underline underline-offset-4 hover:text-orange-400">ARCHIVE</li>
              <li className="font-extrabold text-xs hover:underline underline-offset-4 hover:text-orange-400">TALK SHOW</li>
              <li className="font-extrabold text-xs hover:underline underline-offset-4 hover:text-orange-400">CONTACT</li>
              <li className="font-extrabold text-xs hover:underline underline-offset-4 hover:text-orange-400">PROJECTS</li>
              <li className="font-extrabold text-xs hover:underline underline-offset-4 hover:text-orange-400">PORTFOLIO</li>
            </ul>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
